apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
#There are different types
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=
#the values here are base64 encoded