apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: vote-app
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
        - name: api
          image: bibhash1996/vote-app-server:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_CONNECTION_STRING
              value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/sample_mflix?replicaSet=rs0
            - name: DATABASE
              value: sample_mflix
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
