apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: vote-app
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
        - name: frontend
          image: bibhash1996/vote-app-client:latest
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_SERVER_URL
              value: $API_ELB_PUBLIC_FQDN #add your API_Load_Balancer DNS manually here if app does not run
          ports:
            - containerPort: 8080
