kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testadminbinding
  namespace: rbac-test
subjects:
  - kind: ServiceAccount
    name: foo
    apiGroup: ""
roleRef:
    apiGroup: ""
    kind: Role
    name: testadmin
