apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-hello
  template:
    metadata:
      labels:
        app: helm-hello
    spec:
      containers:
        - name: helm-hello
          image: neilpeterson/aks-helloworld:v1
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: {{.Values.title}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
spec:
  type: {{ .Values.serviceType}}
  ports:
    - port: 80
  selector:
    app: helm-hello
